### ISSUE TITLE
bug: node-fetch-native/proxy 

### ISSUE THREAD

**Issue by tkjaergaard** [unjs/node-fetch-native#114]
### Environment

Bun v.1.0.26

### Reproduction

Git repo: https://github.com/tkjaergaard/giget-bun-reproduction

**Steps to reproduce**:

1. Clone repository
2. Install Bun version 1.0.26 (https://bun.sh/)
3. Run bun install to install dependencies
4. Run build command

```bash
$ bun build index.ts --outdir=dist --target=node
```

### Describe the bug

When build the project using Bun, a "No matching export" error is thrown.

### Additional context

Issue discovered when using `unjs/giget`

[Original issue: #145](https://github.com/unjs/giget/issues/145)

### Logs

```sh
11 | import { fetch } from 'node-fetch-native/proxy';
              ^
error: No matching export in "node_modules/node-fetch-native/dist/proxy.cjs" for import "fetch"
    at /Users/thomaskjaergaard/projects/internal/giget-bun-reproduction/node_modules/giget/dist/index.mjs:11:10
```

**Comment by tkjaergaard** [comment]
The issue either resides in the `build.config.ts`
https://github.com/unjs/node-fetch-native/blob/main/build.config.ts#L30

Or in the `package.json´ file
[https://github.com/unjs/node-fetch-native/blob/main/package.json#L84-L87](https://github.com/unjs/node-fetch-native/blob/main/package.json#L84-L87)

If line 84-87 is removed, the build succeeds.

**Comment by pi0** [comment]
Released 1.6.2. Let me know if it didn't work 👍🏼

**Comment by tkjaergaard** [comment]
@pi0 It works. Build is successful 🙌

**Comment by SamirDhoke** [comment]
hey i was trying to do bun build with target = bun, its breaking with the same issue

**Comment by tuler** [comment]
Issue still happening with me, with `giget~2.0.0`

```
21 | import { fetch } from 'node-fetch-native/proxy';
              ^
error: No matching export in "../../node_modules/.bun/node-fetch-native@1.6.6/node_modules/node-fetch-native/dist/proxy.cjs" for import "fetch"
    at .<redacted>/node_modules/.bun/giget@2.0.0/node_modules/giget/dist/shared/giget.OCaTp9b-.mjs:21:10

Bun v1.3.5 (macOS arm64)
```

**Comment by echoomy** [comment]
Hi. Still happening with `giget@2.0.0` on `bun build` command. Bun v1.3.9.

**Comment by pi0** [comment]
Giget v3 (prerelease) doesn’t have dependability on this lib anymore.

**Comment by echoomy** [comment]
`prisma@7.4.1` still relies on `giget@2.0.0`. In my case, I just overrode the `giget` version to `3.1.2` in my `package.json` for now:

```
"overrides": {
  "giget": "3.1.2"
},
```

Hope this helps anyone with the same issue.
