### ISSUE TITLE
missing Node  polyfill

### ISSUE THREAD

**Issue by reslear** [unjs/node-fetch-native#54]
### Environment

nuxt 3.2.2
polyfill 1.0.2

### Reproduction

polyfill

### Describe the bug

polyfill

### Additional context

<img width="494" alt="Screenshot 2023-02-17 at 20 59 50" src="https://user-images.githubusercontent.com/12596485/219780752-67d46c46-adc3-4aba-b4d4-947a7b4ce416.png">

<img width="316" alt="Screenshot 2023-02-17 at 21 01 35" src="https://user-images.githubusercontent.com/12596485/219780974-0790371b-bf1f-4b7e-b7dd-c3be905ffbaa.png">

**Comment by reslear** [comment]
temp solution: `"node-fetch-native": "1.0.1",`

**Comment by pi0** [comment]
Checking nfn `1.0.2` [dist exists](https://unpkg.com/browse/node-fetch-native@1.0.2/dist/). . This might be a result of npm hoisting behavior with nitro externals. 

Please try `npm nuxt upgrade --force` and open an issue in Nuxt repository if still not fixed 🙏🏼
