### ISSUE TITLE
NUXT Build failing in vercel due to # Character

### ISSUE THREAD

**Issue by harshadsatra** [unjs/node-fetch-native#59]
### Environment

Node: 16.x
Framework: Nuxt.js
Platform: vercel

### Reproduction

NUXT Build

### Describe the bug

Node: 16.x
Framework: Nuxt.js
Platform: vercel
<img width="1440" alt="Screenshot 2023-03-02 at 12 23 22 AM" src="https://user-images.githubusercontent.com/5407138/222240091-a5a0ef59-0fcf-4698-abfb-4f530b0373ea.png">

**Comment by buglavecz** [comment]
Hi. Follow this: https://github.com/nuxt/nuxt/issues/10751

**Comment by harshadsatra** [comment]
@buglavecz 
Thank you for the link, 

I tried the solutions provided, It did not work for me, any other recommendations?

Node: 16.16.0
Nuxt: 2.15.7

**Comment by pi0** [comment]
Downstream issue should be fixed now.
